### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by ahaavisto** [Triviaali/CFR#1]
Koodi on rakenteeltaan helppolukuista, selkeää ja kommentoitu hyvin. Testejä on tehty heti alusta asti, ja niiden kattavuus on hyvä, eli sekin puoli on mennyt hyvin.

En osaa pythonia hyvin, joten en valitettavasti osaa kommentoida koodia yksityiskohtaisesti. Meinasin ensin kirjoittaa, että onpas monta luokkaa samassa tiedostossa, mutta toisaalta se taitaa pythonia tehdessä olla tavanomainen tyyli. Luokat olivat lyhyitä ja hoitivat yhtä asiaa kukin. En kokeillut ajaa testejä, itse ohjelma kyllä pyöri, ja README.md oli simppeli ja hyödyllinen.

Graafista käyttöliittymää ei ole. Tosin ehkä tämänkaltaisessa projektissa se ei välttämätön olekaan? Käyttöliittymä voisi sisältää nykyistä versiota enemmän tietoa siitä, mitä ja miksi ohjelma tekee, tai kysyä syötettä käyttäjältä.

Commitit ovat hyvin isoja, vain muutama commit kattaa oikeastaan kaikki varsinaisen koodin muutokset. Voisi olla parempi tehdä vähän pienemmissä paloissa - jo ihan siksikin, että ongelmien ilmetessä pysyy itse kartalla, missä järjestyksessä muutoksia on tullut, ja milloin ongelmat ehkä ovat alkaneet.

Latasin projektin 14.2. klo 16.

**Comment by Anssikka** [comment]
Kiitos kommenteista!

**Comment by Triviaali** [comment]
Kiitos palautteesta!
