### ISSUE TITLE
Vertaisarviointi #2 - viikko 6

### ISSUE THREAD

**Issue by lauriap** [Triviaali/CFR#2]
Projektin lataushetki: pe 28.2. klo 19:15

Yleiskommentti:
Oppiva algoritmi aiheena vaikuttaa haastavalta! Mikäli ymmärsin algoritmin idean oikein, se näyttää toimivan oikein. Oma alkuoletukseni siis oli, että KSP-pelissä paras strategia on satunnainen seuraavan merkin valinta, jolloin käy järkeen, että optimaalisessa strategiassa molemmat pelaajat pelaavat kutakin merkkiä suurin piirtein yhtä monta kertaa ( = pitkällä aikavälillä satunnaisesti).

Muita kommentteja: 

* Käynnistysohjeet olivat simppelit ja sain helposti ajettua ohjelman.

* Testien ajamisessa minulla sen sijaan oli ongelmia. Se voi osittain johtua omasta kokemuksen puutteesta, mutta voi myös olla, että koodissa on vikaa. Sain sekä test_KUHNS.py:stä että test_RPS.py:stä syntax errorit, ensimmäisessä riviltä 13 ja toisessa riviltä 11 seuraavasti:

```

Tests/test_KUHNS.py:1: in <module>
    from ..Models.KUHNS_CFR import KuhnsPokerCFR
E     File "/home/lauri/Documents/Kuhn/CFR-master/src/Models/KUHNS_CFR.py", line 13
E       information_set: InformationSet
E                      ^
E   SyntaxError: invalid syntax



Tests/test_RPS.py:1: in <module>
    from ..Models.RPS_CFR import Trainer
E     File "/home/lauri/Documents/Kuhn/CFR-master/src/Models/RPS_CFR.py", line 11
E       self.regret_sum: SuperArray
E                      ^
E   SyntaxError: invalid syntax
```

Nuo kannattaa katsoa ennen palautusta kuntoon tai mikäli vika oli testaajassa, selkeyttää testausohjeita.

* Mitä dokumentaatioon tulee, kaipasin hieman parempaa selvennystä eri luokille ja metodeille ohjelmassa. Olit nimennyt luokat mielestäni oikein hyvin ja selkeästi, mutta välillä oli vaikeaa seurata, mitä yksittäiset metodit tekivät. Alkuun voisi kirjoittaa jonkin yleisen kuvauksen luokasta, joka selventäisi sen tarkoitusta. Pythonille on käsittääkseni olemassa PythonDoc, joka voisi olla kätevä työkalu tähän tarkoitukseen.

* Testien testikattavuus näyttää oikein hyvältä! Katsoin myös pikaisesti testien laatua, ja ainakin tarkastamani testit näyttivät kohtuullisen robusteilta. Hienoa!

* Määrittelydokumentti on hyvä ja näyttää siltä, että olet hyvin pystynyt noudattamaan alkuperäistä suunnitelmaa!

*  Omat tietorakenteet (ArrayMethods, SuperArray) on toteutettu kurssivaatimusten mukaisesti 

* En löytänyt koodin laadulle omaa testidokumentaatiota (vrt. Checkstyle). Oliko tämä jo tehty? Jos ei, sen voisi ennen palautusta lisätä.

** SUMMA SUMMARUM**

Oikein hyvältä näyttää! Paranna vielä hieman dokumentaatiota ja korjaa (?) pytestin aiheuttamat virheilmoitukset ja homma alkaa olla paketissa! Tsemppiä!

**Comment by Triviaali** [comment]
Kiitos palautteesta. Ohjeet olivat ehkä hieman puutteelliset virtuaaliympäristön pystyttämisen suhteen. Oletan, että se oli vikana koska kloonasin repositorion kahdelle tietokoneelle ja testit ajautuivat mainiosti kun laittoi venvin pystyyn ja aktivoi. Päivitin ohjeita sen osalta. Checkstyle noudattaa pythonin pep8 styleguidea. Kiitos huolellisesta palautteesta.
